---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
spec:
  type: ClusterIP
  selector:
    app: petclinic-deployment
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
