name: deploy to cluster

on:
  push:
    branches:
      - sonar
    paths: .github/workflows/deploy.yml

Jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    steps:
    name: minikube deployment
    run: 
    - kubectl apply -f deployment/app-deployment.yaml
    - kubectl apply -f deployment/app-service.yaml