name: deploy to cluster

on:
  push:
    branches:
      - sonar
    paths: .github/workflows/deploy.yml

jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    #- name: Set up Kubectl
    #  uses: azure/k8s-set-context@v1
    #  with:
    #    kubeconfig: ${{ secrets.KUBECONFIG }}
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A 
    - name: minikube deployment
      run: |
          kubectl apply -f deployment/app-deployment.yaml
          kubectl apply -f deployment/app-service.yaml
          kubectl wait --for=condition=Running deployment/petclinic-deployment
          kubectl expose service petclinic-service --type=NodePort --name=petclinic-service-ext 
    - name: Test service URLs
      run: |
          minikube service list
          minikube service petclinic-service-ext --url