on:
  push:
    branches: master
  
jobs:
  build_image:
    name: build_image
    runs-on: ubuntu-latest
    steps:
      - 
        name: login to docker
        uses: docker/login-action@v3
        with:
          registry: https://hub.docker.com/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
