name: Build and Push Image

on:
  push:
    branches:
      - sonar # the name of your main branch
    paths: .github/workflows/main.yml
  pull_request:
    types: [opened, synchronize, reopened]
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: kedark0kil/petclinic-actions:latest
          #context: petclinic
          file: ../../dockerfile