on:
  push:
    branches: master
  
jobs:
  login:
    runs-on: ubuntu-latest
    name: build_image
    steps:
      - 
        name: login to docker
        uses: docker/login-action@v3.3.0
        with:
          registry: https://www.docker.io/v2/
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
