on:
  push:
    branches: master
  
jobs:
  login:
    runs-on: ubuntu-latest
    name: login
    steps:
      - 
        name: login to docker
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
